org: dakshesh
app: zoomin
service: zoomin
frameworkVersion: '3'

provider:
  name: aws
  deploymentMethod: direct
  httpApi:
    cors: true
  timeout: 15
  tracing:
    lambda: true
  environment:
    AWS_BUCKET_NAME: zoomin-dev-images
    ACCESS_KEY_ID: AKIAYEUNNGGXZZWD3RES
    SECRET_ACCESS_KEY: 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
    EMAIL_SOURCE_ACCOUNT: 'support@zoominlive.com'
    RDS_HOST: zoomin-1.crzgnnp8iqzv.us-west-2.rds.amazonaws.com
    # RDS_HOST: 127.0.0.1
    RDS_PORT: 3306
    RDS_USER: zoomin_dbuser
    # RDS_USER: root
    RDS_PASSWORD: Wk8$b6!xR
    RDS_DB_NAME: zoomin
    JWT_SECRET_KEY: zoominlivesecretkey
    JWT_REFRESH_SECRET_KEY: 2d
    ACCESS_TOKEN_EXPIRY: 1d
    REFRESH_TOKEN_EXPIRY: 1d
    NODE_ENV: production

  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action: 's3:ListBucket'
          Resource:
            - '*'
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:cloudformation:us-west-2:559716053423:stack/zoomin-dev/51663190-43ef-11ed-b517-0625b6019865'
        - Effect: 'Allow'
          Action:
            - 'ses:SendEmail'
            - 'ses:SendRawEmail'
          Resource:
            - 'arn:aws:ses:*'
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
          Resource: '*'

functions:
  userFunction:
    handler: handler.handler
    events:
      - httpApi: '*'
    provisionedConcurrency: 10

  cameraFunction:
    handler: handler.handler
    events:
      - httpApi:
          method: '*'
          path: /api/cams
    provisionedConcurrency: 10

  childFunction:
    handler: handler.handler
    events:
      - httpApi:
          method: '*'
          path: /api/family/child
    provisionedConcurrency: 10
  streamStatisticsFunction:
    handler: handler.handler
    events:
      - httpApi: 'GET /api/dashboard'
    provisionedConcurrency: 10
  familyFunction:
    handler: handler.handler
    events:
      - httpApi:
          method: '*'
          path: /api/family
    provisionedConcurrency: 10
  roomFunction:
    handler: handler.handler
    events:
      - httpApi:
          method: '*'
          path: /api/rooms
    provisionedConcurrency: 10
  watchStreamFunction:
    handler: handler.handler
    events:
      - httpApi:
          method: '*'
          path: /api/watchstream
    provisionedConcurrency: 10
  disableScheduledMembers:
    handler: cron.disableScheduledFamilyAndChild
    events:
      - schedule: rate(1 day)

plugins:
  - serverless-offline
