module.exports = {
  INTERNAL_SERVER_ERROR: "Oops...something went wrong. Please try again or contact support@zoominlive.com.",
  USER_NOT_FOUND: "Invalid username or password. Please try again.",
  LINK_EXPIRED: "The link has expired.",
  VALID_LINK: "The link is valid.",
  AUTH_ERROR: "Authentication error.",
  INVALID_TOKEN: "Invalid or expired token. Please log in again.",

  CAMERA_CREATED: "Camera successfully created.",
  MAX_CAMERA_ALLOWED: "Maximum number of enrolled cameras has been reached.",
  CAMERA_NOT_FOUND: "Camera not found.",
  CAMERA_DELETED: "Camera successfully deleted.",
  STREAM_NOT_FOUND: "Stream not found. The camera has been deleted.",
  CAMERA_UPDATED: "Camera details updated.",
  CAMERA_FIXED: "Camera issue has been fixed.",
  CAMERA_DETAILS: "All camera details.",

  CHILD_CREATED: "New child profile created.",
  CHILD_DETAILS_UPDATED: "Child details updated.",
  CHILD_DELETED: "Child profile deleted.",
  CHILD_SCHEDULED: "Child is scheduled for deactivation on the selected date.",
  CHILD_DISABLED: "Child successfully disabled.",
  CHILD_ENABLED: "Child successfully enabled.",

  STREAM_DATA: "Stream statistics data.",
  RECENT_VIEWER_ADDED: "Recent viewer added.",

  ROOM_CREATED: "New room created.",
  ROOM_UPDATED: "Room details updated.",
  ROOM_DELETED: "Room deleted.",
  ROOM_DETAILS: "All room details.",

  ZONE_CREATED: "New zone created.",
  ZONE_UPDATED: "Zone details updated.",
  ZONE_DELETED: "Zone deleted.",
  ZONE_DETAILS: "All zone details.",
  
  ZONE_TYPE_CREATED: "New zone type created.",
  ZONE_TYPE_UPDATED: "Zone type details updated.",
  ZONE_TYPE_DELETED: "Zone type deleted.",
  ZONE_TYPE_DETAILS: "All zone type details.",

  FAMILY_CREATED: "New family profile created.",
  EMAIL_EXIST: "Email already exists.",
  FAMILY_UPDATED: "Family member details updated.",
  VERIFY_UPDATED_EMAIL: "Please verify the updated email.",
  FAMILY_MEMBER_NOT_FOUND: "Family member not found.",
  FAMILY_DETAILS: "All family details for the user:",
  PARENT_ADDED: "New parent added.",
  FAMILY_DELETED: "Family profile deleted.",
  FAMILY_SCHEDULED: "Family is scheduled for deactivation on the selected date.",
  FAMILY_DISABLED: "Family profile disabled.",
  FAMILY_MEMBER_DISABLED: "Family member disabled.",
  FAMILY_ENABLED: "Family profile enabled.",
  FAMILY_MEMBER_ENABLED: "Family member enabled.",
  FAMILY_MEMBER_PASS_RESET: "Family member password reset successful.",
  PASSWORD_ALREADY_CHANGED: "Password has already been changed. Please verify to change it again.",
  EMAIL_CHANGED: "Email successfully changed.",
  EMAIL_ALREADY_CHANGED: "Email has already been changed.",
  FAMILY_MEMBER_DELETED: "Family member deleted.",

  USER_FOUND: "User found.",
  USER_REGISTERED: "Registration successful. Please check your email to create a new password.",
  USER_REGISTRATION_FAILED: "User registration failed.",
  USER_NOT_VERIFIED: "This account has not been activated.",
  USER_DEACTIVATED: "This account has been temporarily disabled. Please contact your administrator for assistance.",
  NO_ACTIVE_LOCATION_FOUND: "No active location found. Please contact your administrator or support@zoominlive.com.",
  USER_LOGGED_IN: "User logged in.",
  INVALID_PASSWORD: "Invalid username or password. Please try again.",
  PASSWORD_RESET: "Password reset successfully.",
  PASSWORD_RESET_LINK_SENT: "Password reset link sent to your email.",
  IMAGE_UPLOADED: "Image uploaded.",
  IMAGE_DELETED: "Image deleted.",
  PROFILE_UPDATED_EMAIL_ALREADY_EXIST: "Profile updated, but the email already exists. Please use a different email.",
  PROFILE_EDITED_VERIFY_EMAIL: "Profile edited. Please verify the new email address.",
  RESEND_INVITE: "Invitation has been sent to email.",
  PROFILE_EDITED: "Profile edited.",
  PROFILE_DELETED: "Profile deleted.",
  EMAIL_IS_AVAILABLE: "Email is available for use.",
  CAM_PREFERENCE_STORED: "Default camera preferences stored successfully.",
  LOG_DETAILS: "All log details.",
  ROOMS_ADDED: "Rooms added to child.",
  CHILD_ROOM_DELETED: "Room deleted for child.",
  ROOM_SCHEDULER_CHANGED: "Room access schedule changed.",
  DEFAULT_SETTINGS_UPDATED: "Default settings updated.",
  NOTIFICATION_SENT: "Notification sent successfully.",
  NOTIFICATION_SENT_FAIL: "Notification sending failed.",
  LIVE_STREAM_ENDPOINT: "RTMP endpoint retrieved successfully.",
  LIVE_STREAM_UNAUTHORIZED: "User is not authorized to start a live stream.",
  LIVE_STREAM_NOT_ALLOWED: "Only one active stream is allowed per user.",
  LIVE_STREAM_ROOM_NOT_ALLOWED: "Only one active stream per room license is available.",
  LIVE_STREAM_STARTED: "Live stream has started.",
  LIVE_STREAM_STOPPED: "Live stream has stopped.",
  LIVE_STREAM_ALREADY_STARTED: "Live stream is already started.",
  LIVE_STREAM_ALREADY_ENDED: "Stream has already ended and cannot be restarted.",
  LIVE_STREAM_UPLOADED: "Recorded live stream uploaded successfully.",
  LIVE_STREAM_DETAILS: "Live stream details retrieved successfully.",
  LIVE_STREAM_DETAILS_NOT_FOUND: "Live stream details not found.",
  CUSTOMER_FOUND: "Customer found.",
  LOCATION_FOUND: "Location found.",
  LOCATION_NOT_FOUND: "Location not found.",
  LOCATION_ADDED: "Location added.",
  LOCATION_ADD_FAILED: "Failed to add location.",
  CUSTOMER_NOT_FOUND: "Customer not found.",
  CUSTOMER_REGISTERED: "Customer registration successful.",
  CUSTOMER_APPROVAL_CREATED: "Customer approval created.",
  CUSTOMER_REGISTRATION_FAILED: "Customer registration failed.",
  CUSTOMER_EDITED: "Customer profile edited.",
  LOCATION_EDITED: "Location edited.",
  CUSTOMER_DELETED: "Customer profile deleted.",
  LOCATION_DELETED: "Location deleted.",
  CUSTOMER_LOCATIONS_DETAILS: "All location details for customer.",
  RECORDING_DETAILS: "All recording details."
}
