module.exports = {
  INTERNAL_SERVER_ERROR: 'Something went wrong',
  USER_NOT_FOUND: 'Incorrect username or password, please try again!',
  LINK_EXPIRED: 'Link Expired',
  VALID_LINK: 'Link is valid',
  AUTH_ERROR: 'Auth Error',
  INVALID_TOKEN: 'Invalid Token or Token Expired, please Login again',

  CAMERA_CREATED: 'Camera created',
  MAX_CAMERA_ALLOWED: 'cameras are allowed',
  CAMERA_NOT_FOUND: 'Camera not found',
  CAMERA_DELETED: 'Camera Deleted',
  STREAM_NOT_FOUND: 'Stream not found , Camera deleted',
  CAMERA_UPDATED: 'camera details updated',
  CAMERA_DETAILS: `All the cam's Details`,

  CHILD_CREATED: 'New Child Created',
  CHILD_DETAILS_UPDATED: 'child details updated',
  CHILD_DELETED: 'Child Deleted',
  CHILD_SCHEDULED: 'Child is schedlued to disable on selected date',
  CHILD_DISABLED: 'Child successfully disabled',
  CHILD_ENABLED: 'Child successfully enabled',

  STREAM_DATA: 'stream statistics data',

  RECENT_VIEWER_ADDED: 'recent viewer added',

  ROOM_CREATED: 'New Room created',
  ROOM_UPDATED: 'Room details Updated',
  ROOM_DELETED: 'Room Deleted',
  ROOM_DETAILS: `All the room's details for user:`,

  FAMILY_CREATED: 'New  Family Created',
  EMAIL_EXIST: 'Email already exist',
  FAMILY_UPDATED: 'Family member details updated',
  VEIRFY_UPDATED_EMAIL: 'please verify updated email.',
  FAMILY_MEMBER_NOT_FOUND: 'Family member not found',
  FAMILY_DETAILS: "All the family's details for user:",
  PARENT_ADDED: 'New parent added',
  FAMILY_DELETED: 'Family Deleted',
  FAMILY_SCHEDULED: 'Family is schedlued to disable at selected date',
  FAMILY_DISABLED: 'Family disabled',
  FAMILY_ENABLED: 'Family enabled',
  FAMILY_MEMBER_ENABLED: 'Family member enabled',
  FAMIY_MEMBER_PASS_RESET: 'Family member password reset successful',
  PASSWORD_ALREADY_CHANGED: 'password is already changed, please verify again to change password',
  EMAIL_CHANGED: 'Email successfully changed ',
  EMAIL_ALREADY_CHANGED: 'Email is already changed',

  USER_FOUND: 'User found',
  USER_REGISTERED: 'User Registration Successful , please check email to create new password',
  USER_REGISRATION_FAILED: 'User registration failed',
  USER_NOT_VERIFIED: 'This user account has not been activated.',
  USER_DEACTIVATED: 'User is deactivated please contact Administrator',
  USER_LOGGED_IN: 'User logged in',
  INVALID_PASSWORD: 'Incorrect username or password, please try again!',
  PASSWORD_RESET: 'Password reset successfully',
  PASSWORD_RESET_LINK_SENT: 'Password reset link sent to your email',
  IMAGE_UPLOADED: 'Image uploaded',
  IMAGE_DELETED: 'Image deleted',
  PROFILE_UPDATED_EMAIL_ALREADY_EXIST:
    'User profile edited ,email already exist plese use different email',
  PROFILE_EDITED_VERIFY_EMAIL: 'User profile edited , please verify new email address',
  PROFILE_EDITED: 'User profile edited',
  PROFILE_DELETED: 'User profile deleted',
  EMAIL_IS_AVAILABLE: 'Email is available to use'
};
