module.exports = {
  INTERNAL_SERVER_ERROR:
    'Oops...something went wrong. Please try again or contact support@zoominlive.com',
  USER_NOT_FOUND: 'Incorrect username or password, please try again!',
  LINK_EXPIRED: 'Link Expired',
  VALID_LINK: 'Link is valid',
  AUTH_ERROR: 'Auth Error',
  INVALID_TOKEN: 'Invalid Token or Token Expired, please Login again',

  CAMERA_CREATED: 'Camera created',
  MAX_CAMERA_ALLOWED: 'cameras are allowed',
  CAMERA_NOT_FOUND: 'Camera not found',
  CAMERA_DELETED: 'Camera Deleted',
  STREAM_NOT_FOUND: 'Stream not found , Camera deleted',
  CAMERA_UPDATED: 'camera details updated',
  CAMERA_DETAILS: `All the cam's Details`,

  CHILD_CREATED: 'New Child Created',
  CHILD_DETAILS_UPDATED: 'child details updated',
  CHILD_DELETED: 'Child Deleted',
  CHILD_SCHEDULED: 'Child is schedlued to disable on selected date',
  CHILD_DISABLED: 'Child successfully disabled',
  CHILD_ENABLED: 'Child successfully enabled',

  STREAM_DATA: 'stream statistics data',

  RECENT_VIEWER_ADDED: 'recent viewer added',

  ROOM_CREATED: 'New Room created',
  ROOM_UPDATED: 'Room details Updated',
  ROOM_DELETED: 'Room Deleted',
  ROOM_DETAILS: `All the room's details for user:`,

  FAMILY_CREATED: 'New  Family Created',
  EMAIL_EXIST: 'Email already exist',
  FAMILY_UPDATED: 'Family member details updated',
  VEIRFY_UPDATED_EMAIL: 'please verify updated email.',
  FAMILY_MEMBER_NOT_FOUND: 'Family member not found',
  FAMILY_DETAILS: "All the family's details for user:",
  PARENT_ADDED: 'New parent added',
  FAMILY_DELETED: 'Family Deleted',
  FAMILY_SCHEDULED: 'Family is schedlued to disable at selected date',
  FAMILY_DISABLED: 'Family disabled',
  FAMILY_MEMBER_DISABLED: 'Family member disabled',
  FAMILY_ENABLED: 'Family enabled',
  FAMILY_MEMBER_ENABLED: 'Family member enabled',
  FAMIY_MEMBER_PASS_RESET: 'Family member password reset successful',
  PASSWORD_ALREADY_CHANGED: 'password is already changed, please verify again to change password',
  EMAIL_CHANGED: 'Email successfully changed ',
  EMAIL_ALREADY_CHANGED: 'Email is already changed',
  FAMILY_MEMBER_DELETED: 'Family member deleted',

  USER_FOUND: 'User found',
  USER_REGISTERED: 'User Registration Successful , please check email to create new password',
  USER_REGISRATION_FAILED: 'User registration failed',
  USER_NOT_VERIFIED: 'This user account has not been activated.',
  USER_DEACTIVATED: 'This account has been temporarily disabled. Please contact your administrator for assistance.',
  USER_LOGGED_IN: 'User logged in',
  INVALID_PASSWORD: 'Incorrect username or password, please try again!',
  PASSWORD_RESET: 'Password reset successfully',
  PASSWORD_RESET_LINK_SENT: 'Password reset link sent to your email',
  IMAGE_UPLOADED: 'Image uploaded',
  IMAGE_DELETED: 'Image deleted',
  PROFILE_UPDATED_EMAIL_ALREADY_EXIST:
    'User profile edited ,email already exist plese use different email',
  PROFILE_EDITED_VERIFY_EMAIL: 'User profile edited , please verify new email address',
  RESEND_INVITE: 'Invitation has been sent to email',
  PROFILE_EDITED: 'User profile edited',
  PROFILE_DELETED: 'User profile deleted',
  EMAIL_IS_AVAILABLE: 'Email is available to use',

  CAM_PREFERENCE_STORED: 'default cams stored successfully',
  LOG_DETAILS: "All the log's details",

  ROOMS_ADDED: 'Rooms added in child.',
  CHILD_ROOM_DELETED: 'Room deleted for child.',

  ROOM_SCHEDULER_CHANGED: 'Room access schedule changed',
  NOTIFICATION_SENT: 'Notification sent successfully',
  NOTIFICATION_SENT_FAIL: 'Notification sent fail',

  LIVE_STREAM_ENDPOINT: 'RTMP endpoint retrived successfully',
  LIVE_STREAM_UNAUTHORIZE: 'This user is not authorized to start a live stream',
  LIVE_STREAM_NOT_ALLOWED: 'Only one active stream is allowed per user',
  LIVE_STREAM_ROOM_NOT_ALLOWED: 'Only one active stream per room license is available.',
  LIVE_STREAM_STARTED: 'Live stream has started',
  LIVE_STREAM_STOPPED: 'Live stream has stopped',
  LIVE_STREAM_ALREADY_STARTED: 'Live stream is already started',
  LIVE_STREAM_ALREADY_ENDED: 'Stream Has Already Ended and Can’t Be Started',
  LIVE_STREAM_UPLOADED: 'Recorded live stream uploaded successfully',
  LIVE_STREAM_DETAILS: 'Live stream details retrived successfully',
  LIVE_STREAM_DETAILS_NOT_FOUND: 'Live stream details not found',

  CUSTOMER_FOUND: 'Customer found',
  LOCATION_FOUND: 'Location found',
  LOCATION_ADDED: 'Location Added',
  LOCATION_ADD_FAILED: 'Adding Location Failed',
  CUSTOMER_NOT_FOUND: 'Customer not found',
  CUSTOMER_REGISTERED: 'Customer Registration Successful',
  CUSTOMER_REGISRATION_FAILED: 'Customer registration failed',
  CUSTOMER_EDITED: 'Customer profile edited',
  LOCATION_EDITED: 'Location edited',
  CUSTOMER_DELETED: 'Customer profile deleted', 
  LOCATION_DELETED: 'Location deleted', 
  CUSTOMER_LOCATIONS_DETAILS: `All the location's details for customer`,

  RECORDING_DETAILS: "All the recording's details",
};
